### ISSUE TITLE
Deck Class

### ISSUE THREAD

**Issue by joseRFernandez** [team-awesome1/awesome_cards#6]
Acceptance Criteria 
  - [x] A helper function that can generate a standard deck of 52 unique cards
  - [x] 2 tests to prove expected behavior
  - [x] shuffle function

**Comment by joseRFernandez** [comment]
@

**Comment by samuelhatcliff** [comment]
on it!

**Comment by samuelhatcliff** [comment]
`class Deck {
    constructor() {
        this.cards = ["AS", "2S", "3S", "4S", "5S", "6S", "7S", "8S", "9S", "0S", "JS", "QS", "KS",
            "AD", "2D", "3D", "4D", "5D", "6D", "7D", "8D", "9D", "0D", "JD", "QD", "KD",
            "AC", "2C", "3C", "4C", "5C", "6C", "7C", "8C", "9C", "0C", "JC", "QC", "KC",
            "AH", "2H", "3H", "4H", "5H", "6H", "7H", "8H", "9H", "OH", "JH", "QH", "KH"] //value of 10 is given the code of 0 for indexing purposes
        this.shuffled = false;
        this.deck = this.cards.slice(0, this.cards.length); //property to keep track of deck that will change with gameplay. uses slice to create copy so that cards is property is preserved
        this.remaining = this.deck.length;
    }

    shuffle() {
        const deck = this.deck;
        for (let i = deck.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [deck[i], deck[j]] = [deck[j], deck[i]];
        }
        this.shuffled = true;
        return deck;
        //source: https://stackoverflow.com/questions/2450954/how-to-randomize-shuffle-a-javascript-array
    }

    draw() {
        if (!this.deck.length) {
            throw new RangeError("There are no more cards in the deck! Create a new deck instance or reset current.");
        }
        const card = this.deck.pop();
        this.remaining = this.deck.length--;
        return card
    }

    reset() {
        this.deck = this.cards.slice(0, this.cards.length);
        this.shuffled = false;
        this.remaining = this.deck.length;
    }
}`

**Comment by samuelhatcliff** [comment]
@joseRFernandez, @PatrickSontag 
Here is a rough draft. 
The cards property (written in the constructor as this.cards) is a fixed property that holds all codes for every card in order). 
The deck property (this.deck) keeps track of the current state of deck as the game progresses. 
Shuffle method shuffles the deck
Shuffle property is a boolean indicating whether or not deck is shuffled 
The remaining property is basically a short-hand and easier to read version of deck.length
Draw method pops a card off the deck
Reset method basically imitates creating a new instance of deck (very similar to constructor) except it's called on the same instance. Wasn't sure if we would need this or not, but thought it'd be nice to have just in case. 

Let me know if you guys have any thoughts/questions.

**Comment by samuelhatcliff** [comment]
`    deal() {
        const hands = [this.deck.slice(0, 26), this.deck.slice(26, 52)]
        this.remaining = 0
        return hands
    }

    draw(hand) {
        if (!hand.length) {
            throw new RangeError("There are no more cards in the deck! Create a new deck instance or reset current.");
        }
        const card = hand.pop();
        return card
    }`

rewritten deck and draw functions. @joseRFernandez I'm thinking the draw method as a part of this class might not be necessary, as it is essentially just the native pop() method, which could easily be called outside of the class on the array of cards for p1/p2, and since we wanted to account for players respective cards using state outside of this class, there doesn't seem to be any need to decrement or add any additional functionality to the deck class itself.  Unless you or anyone else can think of a need for it, I'll probably be removing it in the next pull request. 

Deal is pretty simple and self-explanatory. We just need to make sure we remember to call shuffle prior.

**Comment by joseRFernandez** [comment]
ok so a few thoughts --
starting with the deal method :  while there is nothing wrong with having a
strict values for the const hands
*const hands = [this.deck.slice(0, 26), this.deck.slice(26, 52)].*the
re-write makes it solve only one specific problem --- that of a 1v1 game of
war.  a more dynamic solution (and while we may never make a variation game
which would require it) would be better.  only pushing for a more dynamic
approach because you will definitely hear this request in the real world.
so im trying to get you to think about this now.

the draw method is up to you.  you are right.  we don't technically need
it.  HOWEVER, since we are sticking to a OOP approach it makes sense to
stay consistent and assign all of our deck's methods inside of the class.
i will leave that choice to you.  i'd just say to think about the pro's and
cons of your solution.

**Comment by samuelhatcliff** [comment]
Yeah, I was wanting to make the deal method dynamic based on how many players there are, but ran into the issue of 52 not being divisible by 3, 5, etc. 

I'm cool with you wanting something more dynamic, and I'd prefer that too. So, now that I'm looking at this again, I think we could make the method dynamic based on how many cards should be drawn. The downside to this would be that we would need to call this same method as many times as there are players in the game, instead of just once. But I think this is an alright compromise and would be the most re-usable solution. 

I'll edit this then re-submit. 
And we'll keep the draw method!
